#!/bin/bash

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install virtualbox
brew install caskroom/cask/brew-cask
brew cask install virtualbox

# Install docker
brew install docker
brew install boot2docker

boot2docker init
boot2docker up
docker pull ianconnolly/tcd-swift